models/SmnTelefonos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "SIMON.smn_telefonos".
 *
 * @property integer $id
 * @property string $telefono
 * @property string $tipo_telefono
 * @property string $created_at
 * @property string $created_by
 * @property string $updated_at
 * @property string $updated_by
 *
 * @property SIMONSmnMediosTelefonos[] $sIMONSmnMediosTelefonos
 * @property SIMONSmnMedios[] $medios
 * @property SIMONSmnPersonasTelefonos[] $sIMONSmnPersonasTelefonos
 * @property SIMONSmnPersonas[] $personas
 * @property SIMONSmnSolicitantesTelefonos[] $sIMONSmnSolicitantesTelefonos
 * @property SIMONSmnSolicitantes[] $solicitantes
 */
class SmnTelefonos extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'SIMON.smn_telefonos';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['telefono'], 'required'],
            [['telefono'], 'integer'],
            [['telefono', 'tipo_telefono', 'created_by', 'updated_by'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['telefono'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'telefono' => 'Teléfono',
            'tipo_telefono' => 'Tipo Telefono',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    public static function buscarTelefonoPersona($cedula){
        $condicion= ['cedula'=> $cedula];
        //$model = SmnPersonas::find($cedula)->where($condicion)->one();
        //$modelPersonaTelefono= SmnPersonasTelefonos::find()->where(['id_persona'=>$model->id])->one();
        //$modelTelefono= SmnTelefonos::find()->where(['id'=>$modelPersonaTelefono->id_telefono])->one();
        /*echo "<pre>";
        print_r($modelTelefono);
        echo "</pre>";*/
        return $modelTelefono;

    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSmnMediosTelefonos()
    {
        return $this->hasMany(SmnMediosTelefonos::className(), ['id_telefono' => 'id_telefono']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiamMedios()
    {
        return $this->hasMany(SiamMedios::className(), ['id' => 'id_medio'])->viaTable('smn_medios_telefonos', ['id_telefono' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSmnPersonasTelefonos()
    {
        return $this->hasMany(SmnPersonasTelefonos::className(), ['id_telefono' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPersonas()
    {
        return $this->hasMany(SmnPersonas::className(), ['id' => 'id_persona'])->viaTable('smn_personas_telefonos', ['id_telefono' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSmnSolicitantesTelefonos()
    {
        return $this->hasMany(SmnSolicitantesTelefonos::className(), ['id_telefono' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSolicitantes()
    {
        return $this->hasMany(SmnSolicitantes::className(), ['id' => 'id_solicitante'])->viaTable('smn_solicitantes_telefonos', ['id_telefono' => 'id']);
    }
}

controllers/SmnTelefonosController.php
<?php
namespace app\controllers;
use Yii;
use yii\web\Controller;
use yii\web\Response;
use app\models\SmnPersonas;
use app\models\SiamMedios;
use app\models\SmnTelefonos;
use app\models\SmnPersonasTelefonos;
use app\models\SmnMediosTelefonos;
use app\models\SmnSolicitantes;
use app\models\SmnSolicitantesTelefonos;
use yii\widgets\ActiveForm;
use yii\web\NotFoundHttpException;
use yii\base\ErrorException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;


class SmnTelefonosController extends \yii\web\Controller
{
    public function behaviors(){
        return [
            'ghost-access'=> [
                'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
            ],
        ];
    }

    public function actionListarTelefonos(){
        $idPersona=$_POST['id_persona'];
        $model = SmnPersonas::findOne($idPersona);
        $personasTelefonos=$model->smnPersonasTelefonos;
        return $this->renderPartial('listar-telefonos',compact('personasTelefonos'));
    }

    public function actionListarTelefonosMedios(){
        $idMedio=$_POST['id_medio'];
        $model = SmnMediosTelefonos::find()->where(['id_medio'=>$idMedio])->all();
        $MediosTelefonos=$model;
        return $this->renderPartial('listar-telefonos-medios',compact('MediosTelefonos'));
    }

    public function actionMostrarTelefonosMedios(){
        $idMedio=$_POST['id_medio'];
        $model = SmnMediosTelefonos::find()->where(['id_medio'=>$idMedio])->all();
        $MediosTelefonos=$model;
        return $this->renderPartial('mostrar-telefonos-medios',compact('MediosTelefonos'));
    }
    
    public function actionMostrarTelefonosSolicitantes(){
        $idSolicitante=$_POST['id_solicitante'];
        $model = SmnMediosTelefonos::find()->where(['id_solicitante'=>$idSolicitante])->all();
        $SolicitantesTelefonos=$model;
        return $this->renderPartial('mostrar-telefonos-solicitantes',compact('SolicitantesTelefonos'));
    }

    public function actionBuscarTelefono(){
        $id=$_POST['id'];
        $modelTelefono= SmnPersonasTelefonos::find()->where(['id_persona'=>$id])->one();

    }

    public function actionAgregarTelefonosMippci(){
        if(isset($_POST['id_persona'])){
            $idPersona = $_POST['id_persona'];
        }else{
            $idPersona = $_POST['SmnTelefonos']['id_persona'];
        }
        $model=new SmnTelefonos;
        
        if(isset($_POST['SmnTelefonos'])){
            $telefono=$_POST['SmnTelefonos']['telefono'];
            $idPersona=$_POST['SmnTelefonos']['id_persona'];
            $connection = \Yii::$app->db;
            $transaction = $connection->beginTransaction();
            try {
                $model->telefono=$telefono;
                if($model->validate()){
                    $model->save();
                    $modelPersonaTelefono = new smnPersonasTelefonos;
                    $modelPersonaTelefono->id_persona = $idPersona;
                    $modelPersonaTelefono->id_telefono = $model->id;
                    $modelPersonaTelefono->save();
                }else{
                    throw new ErrorException('Error Registrando Teléfono'.$model->telefono);
                }

                $transaction->commit();
                return true;
                //$this->redirect(array(Url::previous()));
            }catch(ErrorException $e){
                $transaction->rollback();
            }
        }
        return $this->renderPartial('agregar-telefonos-mippci',compact('model','idPersona'));
    }
    
    public function actionAgregarTelefonos(){
    	$model=new SmnTelefonos;
    	if(isset($_POST['SmnTelefonos'])){
    		$telefono=$_POST['SmnTelefonos']['telefono'];
    		$idPersona=$_POST['SmnPersonas']['id'];
    		$connection = \Yii::$app->db;
            $transaction = $connection->beginTransaction();
            try {
                //registro de telefonos y asignación de telefonos a la persona registrada            
                $model->telefono=$telefono;
                if($model->validate()){
                    $model->save();
                    $modelPersonaTelefono=new smnPersonasTelefonos;
                    $modelPersonaTelefono->id_persona=$idPersona;
                    $modelPersonaTelefono->id_telefono=$model->id;
                    $modelPersonaTelefono->save();
                }else{
                    throw new ErrorException('Error Registrando Telefono'.$model->telefono);
                }

                $transaction->commit();
            }catch(ErrorException $e){
                $transaction->rollback();

            }
            exit();
    	}

        if(isset($_POST['usuario_medio'])){
            $correo=$_POST['SmnTelefonos']['telefono'];
            $idPersona=$_POST['id_persona'];
            $connection = \Yii::$app->db;
            $transaction = $connection->beginTransaction();
            try{
                //registro de correos y asignación de correos a la persona registrada            
                $model->telefono=$telefono;
                if($model->validate()){
                    $model->save();
                    $modelPersonaTelefono=new smnPersonasTelefonos;
                    $modelPersonaTelefono->id_persona=$idPersona;
                    $modelPersonaTelefono->id_telefono=$model->id;
                    $modelPersonaTelefono->save();
                    die();
                }else{
                    throw new ErrorException('Error Registrando Correo'.$model->correo);
                }

                $transaction->commit();
                return $modelPersonaTelefono;
            }catch(ErrorException $e){
                $transaction->rollback();
            }
            exit();
        }

    	$idPersona=$_POST['id_persona'];
    	$modelPersona=SmnPersonas::findOne($idPersona);

    	return $this->renderPartial('agregar-telefonos',compact('model','modelPersona'));
    }

	public function actionValidarTelefonos(){
    	$telefono=Yii::$app->request->post()['valor'];
        $model=new SmnTelefonos;
      	$model->telefono=$telefono;
       	if(!$model->validate()){
            print_r($model->errors['telefono'][0]);
        }
    }

    public function actionEliminarPersonasTelefonos(){
        $idPersona=$_POST['id_persona'];
        $idTelefono=$_POST['id_telefono'];
        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();
        try {           
            $modelPersonaTelefono=SmnPersonasTelefonos::find()->where(['id_persona'=>$idPersona,'id_telefono'=>$idTelefono])->one();
            $modelTelefono=SmnTelefonos::findOne($idTelefono);
            $modelPersonaTelefono->delete();
            $modelTelefono->delete();
            $transaction->commit();
        }catch(ErrorException $e){
            $transaction->rollback();
        }
    }


    public function actionEliminarSolicitantesTelefonos(){
        $idSolicitante=$_POST['id_solicitante'];
        $idTelefono=$_POST['id_telefono'];
        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();
        try{
            $modelSolicitanteTelefono=SmnSolicitantesTelefonos::find()->where(['id_solicitante'=>$idSolicitante,'id_telefono'=>$idTelefono])->one();
            $modelTelefono=SmnTelefonos::findOne($idTelefono);
            $modelSolicitanteTelefono->delete();
            $modelTelefono->delete();
            $transaction->commit();
        }catch(ErrorException $e){
            $transaction->rollback();
        }
    }


    public function actionListarTelefonosSolicitantes(){
        $idSolicitante=$_POST['id_solicitante'];
        $model = SmnSolicitantes::findOne($idSolicitante);
        $solicitantesTelefonos=$model->smnSolicitantesTelefonos;
        return $this->renderPartial('listar-telefonos-solicitantes',compact('solicitantesTelefonos'));
    }

    public function actionAgregarTelefonosSolicitantes(){
        $model=new SmnTelefonos;
        if(isset($_POST['SmnTelefonos'])){
            $telefono=$_POST['SmnTelefonos']['telefono'];
            $idSolicitante=$_POST['SmnSolicitantes']['id'];
            $connection = \Yii::$app->db;
            $transaction = $connection->beginTransaction();
            try {
                //registro de telefonos y asignación de telefonos a la persona registrada            
                $model->telefono=$telefono;
                if($model->validate()){
                    $model->save();
                    $modelSolicitanteTelefono=new smnSolicitantesTelefonos;
                    $modelSolicitanteTelefono->id_solicitante=$idSolicitante;
                    $modelSolicitanteTelefono->id_telefono=$model->id;
                    $modelSolicitanteTelefono->save();
                }else{
                    throw new ErrorException('Error Registrando Telefono'.$model->telefono);
                }

                $transaction->commit();
            }catch(ErrorException $e){
                $transaction->rollback();

            }
            exit();
        }

        $idSolicitante=$_POST['id_solicitante'];
        $modelSolicitante=SmnSolicitantes::findOne($idSolicitante);

        return $this->renderPartial('agregar-telefonos-solicitantes',compact('model','modelSolicitante'));
    }
    
        public function actionListarTelefonosPersonas(){
        $idPersona=$_POST['id_persona'];
        $model = SmnPersonas::findOne($idPersona);
        $personasTelefonos=$model->smnPersonasTelefonos;
        return $this->renderPartial('listar-telefonos-personas',compact('personasTelefonos'));
    }


    public function actionAgregarTelefonosPersonas(){
        $idPersona = $_POST['id_persona'];
        $model=new SmnTelefonos;
        
        if(isset($_POST['SmnTelefonos'])){
            $telefono=$_POST['SmnTelefonos']['telefono'];
            $idPersona=$_POST['SmnTelefonos']['id_persona'];
            $connection = \Yii::$app->db;

views/smn-telefonos/agregar-telefonos-medios.php
<?php
use yii\helpers\Html;
use yii\base\Model;
use kartik\widgets\ActiveForm;
use kartik\widgets\ActiveField;
?>
<script type="text/javascript">
	$(document).on("submit", "#formularioTelefonosMedios", function () {
        data=$(this).serialize();
        respuesta=consultarPHP('/smn-telefonos/agregar-telefonos-medios',data,'html',false);
            bootbox.hideAll();
            if(respuesta == "error"){
                bootbox.alert('Ha ocurrido un error. Por favor intente de nuevo');
            }else{
                bootbox.alert('Correo electrónico registrado con éxito');
            }
        idMedio=$("#id_medio").html();
        return false;

    });

</script>

<?php 

$form = ActiveForm::begin(['id'=>'formularioTelefonosMedios','enableClientValidation'=>true,'enableAjaxValidation'=>true]);

echo $form->field($model, 'id')->hiddenInput()->label(false);

echo $form->field($modelMedios, 'id_medio')->hiddenInput()->label(false);?>
<div class="row">
    <div class="col-md-12"> 
        <?= $form->field($modelMedios, 'id_telefonos')->textInput(['class'=>'item-validar','data-accion-validar'=>'/smn-telefonos/validar-telefonos'])?>
    </div>
</div>

<div class="row">
	<div class="col-md-12">
		<?php
		echo Html::submitButton('Registrar',array('id'=>'registrar-telefono-medio','class'=>'btn btn-success'));
		?>
	</div>
</div>
<?php
ActiveForm::end();
?>

views/smn-telefonos/agregar-telefonos-mippci.php
<?php
use yii\helpers\Html;
use yii\base\Model;
use kartik\widgets\ActiveForm;
use kartik\widgets\ActiveField;
$form = ActiveForm::begin(['id'=>'formularioTelefonosMippci','enableClientValidation'=>true,'enableAjaxValidation'=>true, 'action'=>['smn-telefonos/agregar-telefonos-mippci']]);
echo $form->field($model, "id_persona")->hiddenInput( array('value'=>$idPersona))->label(false);
?>
<div class="row">
    <div class="col-md-12"> 
        <?= $form->field($model, 'telefono')->textInput(['class'=>'item-validar-mippci', 'data-accion-validar-mippci'=>'/smn-telefonos/validar-telefonos'])?>
    </div>
</div>

<div class="row">
	<div class="col-md-12">
		<?php 
                    echo Html::submitButton('Registrar',array('id'=>'registrar-telefonos-mippci','class'=>'item-validar btn btn-success'));
                ?>
	</div>
</div>
<?php
ActiveForm::end();
?>

views/smn-telefonos/agregar-telefonos-personas.php
<?php
use yii\helpers\Html;
use yii\base\Model;
use kartik\widgets\ActiveForm;
use kartik\widgets\ActiveField;
$form = ActiveForm::begin(['id'=>'formularioTelefonosPersonas','enableClientValidation'=>true,'enableAjaxValidation'=>true, 'action'=>['smn-telefonos/agregar-telefonos-personas']]);
echo $form->field($model, "id_persona")->hiddenInput( array('value'=>$idPersona))->label(false);
?>
<div class="row">
    <div class="col-md-12"> 
        <?= $form->field($model, 'telefono')->textInput(['class'=>'item-validar-persona', 'data-accion-validar-persona'=>'/smn-telefonos/validar-telefonos'])?>
    </div>
</div>

<div class="row">
	<div class="col-md-12">
		<?php 
                    echo Html::submitButton('Registrar',array('id'=>'registrar-telefonos-personas','class'=>'item-validar btn btn-success'));
                ?>
	</div>
</div>
<?php
ActiveForm::end();
?>

views/smn-telefonos/agregar-telefonos-solicitantes.php
<?php
use yii\helpers\Html;
use yii\base\Model;
use kartik\widgets\ActiveForm;
use kartik\widgets\ActiveField;


$form = ActiveForm::begin(['id'=>'formularioTelefonos','enableClientValidation'=>true,'enableAjaxValidation'=>true]);

echo $form->field($modelSolicitante, 'id')->hiddenInput()->label(false);
?>
<div class="row">
    <div class="col-md-12"> 
        <?= $form->field($model, 'telefono')->textInput(['class'=>'item-validar','data-accion-validar'=>'/smn-telefonos/validar-telefonos'])?>
    </div>
</div>

<div class="row">
	<div class="col-md-12">
		<?php
		echo Html::submitButton('Registrar',array('id'=>'registrar-telefono','class'=>'btn btn-success'));
		?>
	</div>
</div>
<?php
ActiveForm::end();
?>

views/smn-telefonos/agregar-telefonos-usuarios-medios.php
<?php
use yii\helpers\Html;
use yii\base\Model;
use kartik\widgets\ActiveForm;
use kartik\widgets\ActiveField;
$form = ActiveForm::begin(['id'=>'formularioTelefonosMedios','enableClientValidation'=>true,'enableAjaxValidation'=>true, 'action'=>['smn-telefonos/agregar-telefonos-mippci']]);
echo $form->field($model, "id_persona")->hiddenInput( array('value'=>$idPersona))->label(false);
?>
<div class="row">
    <div class="col-md-12"> 
        <?= $form->field($model, 'telefono')->textInput(['class'=>'item-validar-mippci', 'data-accion-validar-mippci'=>'/smn-telefonos/validar-telefonos'])?>
    </div>
</div>

<div class="row">
	<div class="col-md-12">
		<?php 
                    echo Html::submitButton('Registrar',array('id'=>'registrar-telefonos-mippci','class'=>'item-validar btn btn-success'));
                ?>
	</div>
</div>
<?php
ActiveForm::end();
?>

views/smn-telefonos/agregar-telefonos.php
<script type="text/javascript">
	$(document).ready(function(){
	    /*$(document).on("submit","#formularioTelefonos",function(){
	        data=$(this).serialize();
	        Persona= $("#smnuser-id_persona").val();
	        idPersona=$("#smnuser-cedula").val();
	        data={cedula:idPersona};
	        consulta=consultarPHP('/smn-personas/buscar-persona',data,'json',false);
	        respuesta=consultarPHP('/smn-telefonos/agregar-telefonos',data,'html',false);
	        bootbox.hideAll();
	        if(respuesta == "error"){
	            bootbox.hideAll('Ha ocurrido un error. por favor intente de nuevo');
	        }else{
	            bootbox.alert('Telefono registrado con éxito');
	        }
	        listartelefonos(Persona);
	    
	        return false;
	    });*/
	});
</script>    
<?php
use yii\helpers\Html;
use yii\base\Model;
use kartik\widgets\ActiveForm;
use kartik\widgets\ActiveField;


$form = ActiveForm::begin(['id'=>'formularioTelefonos','enableClientValidation'=>true,'enableAjaxValidation'=>true]);

echo $form->field($modelPersona, 'id')->hiddenInput()->label(false);
?>
<div class="row">
    <div class="col-md-12"> 
        <?= $form->field($model, 'telefono')->textInput(['class'=>'item-validar2','data-accion-validar'=>'/smn-telefonos/validar-telefonos'])?>
    </div>
    <input type="hidden" name="usuario_medio">

</div>

<div class="row">
	<div class="col-md-12">
		<?php
		echo Html::submitButton('Registrar',array('id'=>'registrar-telefono','class'=>'btn btn-success'));
		?>
	</div>
</div>
<?php
ActiveForm::end();
?>

views/smn-telefonos/index.php
<?php
/* @var $this yii\web\View */
?>
<h1>smn-telefonos/index</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

views/smn-telefonos/listar-telefonos-medios.php
<?php
use yii\helpers\Html;
use yii\base\Model;
use kartik\widgets\ActiveForm;
use kartik\widgets\ActiveField;
/*echo "<pre>";
print_r($MediosTelefonos); exit();
echo "</pre>";*/
echo "<center>";
echo Html::button('Agregar Teléfono',array('id'=>'nuevo-telefono-medio','class'=>'btn btn-xs btn-success'));
echo "</center><br>";
if(count($MediosTelefonos) > 0){
	echo "<table>";
		foreach ($MediosTelefonos as $MediosTelefonos){
			echo "<tr>";
				echo "<td>".$MediosTelefonos->idTelefono->telefono."</td>";
				echo "<td>
						&nbsp;&nbsp;&nbsp;&nbsp;
						<input type='button' value='Remover' class='btn btn-xs btn-danger eliminar-telefono margen1' data-id_telefono='".$MediosTelefonos->id_telefono."'>
					</td>";
			echo "</tr>";
		}
	echo "</table>";
}else{
	echo "No existen teléfonos registrados";
}
?>

views/smn-telefonos/listar-telefonos-solicitantes.php
<?php
use yii\helpers\Html;
use yii\base\Model;
use kartik\widgets\ActiveForm;
use kartik\widgets\ActiveField;

echo "<center>";
echo Html::button('Agregar Telefono',array('id'=>'agregar-telefono','class'=>'btn btn-xs btn-success'));
echo "</center><br>";
if(count($solicitantesTelefonos) > 0){
	echo "<table>";
		foreach ($solicitantesTelefonos as $solicitanteTelefono){
			echo "<tr>";
				echo "<td>".$solicitanteTelefono->idTelefono->telefono."</td>";
				echo "<td>
						&nbsp;&nbsp;&nbsp;&nbsp;
						<input type='button' value='Remover' class='btn btn-xs btn-danger margen1 eliminar-telefono' data-id_telefono='".$solicitanteTelefono->id_telefono."'>
					</td>";
			echo "</tr>";
		}
	echo "</table>";
}else{
	echo "No existen teléfonos registrados";
}
?>

views/smn-telefonos/listar-telefonos.php
<?php
use yii\helpers\Html;
use yii\base\Model;
use kartik\widgets\ActiveForm;
use kartik\widgets\ActiveField;


echo "<fieldset class='scheduler-border'>";
	echo "<legend class='scheduler-border'>Teléfonos</legend>";
	
	echo "<left>";
	echo Html::button('Agregar Telefono',array('id'=>'agregar-telefono','class'=>'btn btn-xs btn-success'));
	echo "</left><br>";

	if(count($personasTelefonos) > 0){
		echo "<table align=left>";
			foreach ($personasTelefonos as $personaTelefono){
				echo "<tr>";
					echo "<td class='text-right margen-remover'>".$personaTelefono->telefono->telefono."</td>";
					echo "<td class='margen-remover'>&nbsp;<input type='button' class='btn btn-xs btn-danger eliminar-telefono' data-id_telefono='".$personaTelefono->id_telefono."' value='Remover'></input></td>";
				echo "</tr>";
			}
		echo "</table>";
	}else{
		echo "No existen teléfonos registrados";
	}
echo "</fieldset>";
?>

views/smn-telefonos/mostrar-telefonos-medios.php
<?php
use yii\helpers\Html;
use yii\base\Model;
use kartik\widgets\ActiveForm;
use kartik\widgets\ActiveField;

if(count($MediosTelefonos) > 0){
	echo "<table>";
		foreach ($MediosTelefonos as $MediosTelefonos){
			echo "<tr>";
				echo "<td> "."&nbsp;&nbsp;"."</td>";
				echo "<td> "."<li>"."</li></td>";
				echo "<td> ".$MediosTelefonos->idTelefono->telefono."</td>";
			echo "</tr>";
		}
	echo "</table>";
}else{
	echo "No existen teléfonos registrados";
}
?>

views/smn-telefonos/mostrar-telefonos-solicitantes.php
<?php
use yii\helpers\Html;
use yii\base\Model;
use kartik\widgets\ActiveForm;
use kartik\widgets\ActiveField;

if(count($SolicitantesTelefonos) > 0){
	echo "<table>";
		foreach ($SolicitantesTelefonos as $SolicitantesTelefonos){
			echo "<tr>";
				echo "<td> "."&nbsp;&nbsp;"."</td>";
				echo "<td> "."<li>"."</li></td>";
				echo "<td> ".$SolicitantesTelefonos->idTelefono->telefono."</td>";
			echo "</tr>";
		}
	echo "</table>";
}else{
	echo "No existen teléfonos registrados";
}
?>

views/smn-telefonos/nuevos-telefonos.php
<fieldset class="scheduler-border">    
    <legend class="scheduler-border">Teléfonos</legend>
    <div class="listado-items">
        <div class="form-group field-telefono required">
            <div class="input-group">
                <input type="text" id="telefono" class="form-control item-validar tlf solo-numero" name="SmnTelefonos[telefono][]" readonly="" data-accion-validar="/smn-telefonos/validar-telefonos">
                <span class="input-group-btn">
                    <button type="button" class="agregar-item btn btn-success"><i class="glyphicon glyphicon-plus"></i></button>
                </span>
            </div>
            <div class="help-block"></div>
        </div>
    </div>
</fieldset>