models/SmnSolicitantes.php
<?php
namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\base\ErrorException;

use app\models\SmnCorreos;
use app\models\SmnTelefonos;
use app\models\SmnSolicitantesCorreos;
use app\models\SmnSolicitantesTelefonos;
use app\models\SmnSolicitantesContactos;
use app\models\SmnSolicitanteEstructuraGobierno;


class SmnSolicitantes extends \yii\db\ActiveRecord
{

    public static function tableName()
    {
        return 'SIMON.smn_solicitantes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'id_direccion'], 'required'],
            [['nombre', 'nombre_abreviado', 'created_by', 'updated_by'], 'string'],
            [['id_direccion'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['tipo', 'activo', 'vicepresidencia'], 'boolean'],
            [['id_direccion'], 'exist', 'skipOnError' => true, 'targetClass' => SmnDireccion::className(), 'targetAttribute' => ['id_direccion' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels(){
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'nombre_abreviado' => 'Nombre Abreviado',
            'id_direccion' => 'Id Direccion',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'tipo' => 'Tipo',
            'activo' => 'Activo',
            'vicepresidencia' => 'Vicepresidencia',
        ];
    }

    public function getNomAbreviado(){
        return $this->nombre.'  -  '.$this->nombre_abreviado;
    }

    public function getNombreCompleto(){
        return $this->nombre_abreviado.'  -  '.$this->nombre;
    }

    public function listSolicitantes($idSolicitante = null){
        if($idSolicitante != null){
            $condicion=['activo'=>TRUE,'id'=>$idSolicitante];
        }else{
            $condicion=['activo'=>TRUE];
        }
        $solicitantes=SmnSolicitantes::find()->where($condicion)->orderBy(['nombre'=>SORT_ASC])->all();
        $listSolicitantes=ArrayHelper::map($solicitantes,'id','nomAbreviado');
        return $listSolicitantes;
    }


    public function registrar($post,$model,$direccion){
        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();
        try{
            //registrar una dirección por solicitante
            $direccion->load($post);
            $direccion->id_estado=0;
            $direccion->id_municipio=0;
            $direccion->id_parroquia=0;
            $direccion->id_ciudad=0;
            
            if($direccion->validate()){
                $direccion->save();
            }else{
                $direccion->validate();
                throw new ErrorException('Error Registrando Dirección');
            }
            
            //registrar los datos del solicitante asignandole la dirección previamente registrada
            $model->load($post);
            $model->id_direccion=$direccion->id;
            $model->tipo=TRUE;
            if($model->validate()){
                $model->save();
            }else{
                throw new ErrorException('Error Registrando los datos del solicitante');   
            }

            
            //registro de correos y asignación de correos al solicitante registrado
            foreach ($post['SmnCorreos']['correo'] as $itemCorreo){
                $modelCorreo=new SmnCorreos();
                $modelCorreo->correo=$itemCorreo;
                if($modelCorreo->validate()){
                    $modelCorreo->save();
                    $modelSolicitanteCorreo=new SmnSolicitantesCorreos;
                    $modelSolicitanteCorreo->id_solicitante=$model->id;
                    $modelSolicitanteCorreo->id_correo=$modelCorreo->id;
                    $modelSolicitanteCorreo->save();
                }else{
                    throw new ErrorException('Error Registrando Correo'.$modelCorreo->correo);
                }
            }
            //registro de teléfonos y asignación de teléfonos al solicitante registrado
            foreach ($post['SmnTelefonos']['telefono'] as $itemTelefono){
                $modelTelefono=new SmnTelefonos();
                $modelTelefono->telefono=$itemTelefono;
                if($modelTelefono->validate()){
                    $modelTelefono->save();
                    $modelSolicitanteTelefono=new SmnSolicitantesTelefonos;
                    $modelSolicitanteTelefono->id_solicitante=$model->id;
                    $modelSolicitanteTelefono->id_telefono=$modelTelefono->id;
                    $modelSolicitanteTelefono->save();
                }else{
                    throw new ErrorException('Error Registrando Teléfono'.$modelTelefono->telefono);
                }
            }

            //asignación de contactos al solicitante registrado
            if(isset($post['Contactos'])){
                foreach ($post['Contactos'] as $itemContacto){
                    $modelSolicitanteContacto=new SmnSolicitantesContactos;
                    $modelSolicitanteContacto->id_solicitante=$model->id;
                    $modelSolicitanteContacto->id_persona=$itemContacto['id_persona'];
                    $modelSolicitanteContacto->save();
                }
            }

            $transaction->commit();
            return $model;
        }catch(ErrorException $e){
            echo "<pre>";
            print_r($e);
            echo "</pre>";
            $transaction->rollback();
        }
    }


    public function modificar($post,$model,$direccion){
        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();
        try{
            //registrar una dirección por solicitante
            $direccion->load($post);
            
            if($direccion->validate()){
                $direccion->save();
            }else{
                $direccion->validate();
                throw new ErrorException('Error Modificando Dirección');
            }
            
            //registrar los datos del solicitante asignandole la dirección previamente registrada
            $model->load($post);
            if($model->validate()){
                $model->save();
            }else{
                throw new ErrorException('Error Modificando los datos del solicitante');   
            }

            $transaction->commit();
            return $model;
            
        }catch(ErrorException $e){
            $transaction->rollback();
        }
    }
    

    public function getSmnConvocatorias()
    {
        return $this->hasMany(SmnConvocatorias::className(), ['id_convocante' => 'id']);
    }



    public function getSmnConvocatorias0()
    {
        return $this->hasMany(SmnConvocatorias::className(), ['id_coconvocante' => 'id']);
    }

    

    public function getSmnCuentasExternasSolicitantes()
    {
        return $this->hasMany(SmnCuentasExternasSolicitantes::className(), ['id_solicitante' => 'id']);
    }

    

    public function getSmnEntrevistas()
    {
        return $this->hasMany(SmnEntrevistas::className(), ['id_convocante' => 'id']);
    }

    

    public function getSmnSolicitanteEstructuraGobiernos()
    {
        return $this->hasMany(SmnSolicitanteEstructuraGobierno::className(), ['id_solicitante' => 'id']);
    }

    

    public function getIdEstructuraGobiernos()
    {
        return $this->hasMany(SmnEstructuraGobierno::className(), ['id' => 'id_estructura_gobierno'])->viaTable('smn_solicitante_estructura_gobierno',['id_solicitante' => 'id']);
    }

    

    public function getIdDireccion()
    {
        return $this->hasOne(SmnDireccion::className(),['id' => 'id_direccion']);
    }

    

    public function getSmnSolicitantesContactos()
    {
        return $this->hasMany(SmnSolicitantesContactos::className(),['id_solicitante' => 'id']);
    }

    

    public function getIdPersonas()
    {
        return $this->hasMany(SmnPersonas::className(),['id' => 'id_persona'])->viaTable('smn_solicitantes_contactos', ['id_solicitante' => 'id']);
    }

    

    public function getSmnSolicitantesCorreos()
    {
        return $this->hasMany(SmnSolicitantesCorreos::className(),['id_solicitante' => 'id']);
    }

    

    public function getIdCorreos()
    {
        return $this->hasMany(SmnCorreos::className(), ['id' => 'id_correo'])->viaTable('smn_solicitantes_correo', ['id_solicitante' => 'id']);
    }

    

    public function getSmnSolicitantesTelefonos()
    {
        return $this->hasMany(SmnSolicitantesTelefonos::className(), ['id_solicitante' => 'id']);
    }

    

    public function getIdTelefonos()
    {
        return $this->hasMany(SmnTelefonos::className(), ['id' => 'id_telefono'])->viaTable('smn_solicitantes_telefonos', ['id_solicitante' => 'id']);
    }


    public function listVicepresidencias(){
        $vicepresidencias=SmnSolicitantes::find()->where(['vicepresidencia'=>TRUE])->all();
        $listVicepresidencias=ArrayHelper::map($vicepresidencias,'id','nombre');
        return $listVicepresidencias;
    }
}

controllers/SmnSolicitantesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\SmnSolicitantes;
use app\models\SmnSolicitantesSearch;
use app\models\SmnEstructuraGobierno;
use app\models\SmnDireccion;
use app\models\SmnCorreos;
use app\models\SmnTelefonos;
use app\models\SmnPersonas;
use app\models\SmnSolicitantesTelefonos;
use app\models\SmnSolicitantesCorreo;
use app\models\SmnSolicitanteEstructuraGobierno;
use app\models\SmnSolicitantesContactos;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;


/**
 * SmnSolicitantesController implements the CRUD actions for SmnSolicitantes model.
 */
class SmnSolicitantesController extends SimonController
{
    public function behaviors()
    {
        return [
            'ghost-access'=> [
                'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
            ],
        ];
    }

    /**
     * Lists all SmnSolicitantes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SmnSolicitantesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=10;

        return $this->render('index',[
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single SmnSolicitantes model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view',[
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new SmnSolicitantes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new SmnSolicitantes();
        $telefonos = new SmnTelefonos();
        $correos = new SmnCorreos();
        $direccion = new SmnDireccion();

        if(Yii::$app->request->post()){
            $model=$model->registrar($_POST,$model,$direccion);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create',compact('model','telefonos','correos','direccion'));
    }

    /**
     * Updates an existing SmnSolicitantes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id){
        $model = $this->findModel($id);
        $telefonos = new SmnTelefonos();
        $correos = new SmnCorreos();

        $direccion = SmnDireccion::find()->where(['id'=>$model->id_direccion])->one();
        if($direccion==NULL){
            $direccion=new SmnDireccion();
        }

        if(Yii::$app->request->post()){
            $model=$model->modificar($_POST,$model,$direccion);
            Yii::$app->session->setFlash('success', 'Ente Adscrito modificado con éxito');
            return $this->redirect(['view', 'id' => $model->id]);
        }
        
        return $this->render('update',compact('model','telefonos','correos','direccion'));

    }

    /**
     * Deletes an existing SmnSolicitantes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id){

        $this->findModel($id)->delete();
        return $this->redirect(['index']);

    }

    /**
     * Finds the SmnSolicitantes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SmnSolicitantes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SmnSolicitantes::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionListvicepresidencia(){ 
        $idEstructuraGobierno=Yii::$app->request->post()['idestructuragobierno'];
        $estructuraGobierno=SmnEstructuraGobierno::findOne($idEstructuraGobierno);
        $listVicepresidencias=SmnSolicitantes::listvicepresidencias();
        return $this->renderPartial("viewlistvicepresidencias",compact('estructuraGobierno','listVicepresidencias'));
    }

    public function actionAgregarContacto(){
        $cedula= $_POST['cedula'];
        $solicitanteId=$_POST['solicitante_id'];
        $model=SmnPersonas::buscarPersona($cedula);
        if(!empty($solicitanteId)){
            $modelSolicitanteContacto=new SmnSolicitantesContactos;
            $modelSolicitanteContacto->id_solicitante=$solicitanteId;
            $modelSolicitanteContacto->id_persona=$model->id;
            $modelSolicitanteContacto->save();
        }
        return $this->renderPartial("_filaContacto",compact('model'));
    }

    public function actionRemoverContacto(){
        $idPersona=$_POST['id_persona'];
        $idSolicitante=$_POST['id_solicitante'];

        if(!empty($idSolicitante)){
            $model = SmnSolicitantesContactos::find()->where(['id_solicitante'=>$idSolicitante,'id_persona'=>$idPersona])->one();
            $model->delete();
        }
    }

    public function actionValidarAsociarEstructura(){
        $solicitanteestructuragobierno=SmnSolicitanteEstructuraGobierno::find()->where(
                ['id_solicitante'=>$_POST['id_solicitante'],'id_estructura_gobierno'=>$_POST['id_estructura_gobierno']])
            ->all();
        return count($solicitanteestructuragobierno);
    }

    public function actionAsociarEstructura(){
        $solicitanteestructuragobierno=new SmnSolicitanteEstructuraGobierno;
        $solicitanteestructuragobierno->id_solicitante=$_POST['id_solicitante'];
        $solicitanteestructuragobierno->id_estructura_gobierno=$_POST['id_estructura_gobierno'];
        $solicitanteestructuragobierno->id_vicepresidencia=$_POST['id_vicepresidencia'];
        $solicitanteestructuragobierno->save();

        return $this->renderPartial("_asociarEstructura",compact('solicitanteestructuragobierno'));
    }

    public function actionRemoverAsociarEstructura(){
        $solicitanteestructuragobierno=SmnSolicitanteEstructuraGobierno::find()->where(
                ['id_solicitante'=>$_POST['id_solicitante'],'id_estructura_gobierno'=>$_POST['id_estructura_gobierno']])
            ->one();
        $solicitanteestructuragobierno->delete();
    }


    public function actionValidarRegistroSolicitante(){
        echo "<pre>";
        print_r($_POST);
        echo "</pre>";
    }

}

views/smn-solicitantes/_asociarEstructura.php
<?php
use yii\helpers\Html;
?>

<tr class="table">
	<td><?php echo $solicitanteestructuragobierno->idEstructuraGobierno->nombre ?></td>
	<td><?php echo empty($solicitanteestructuragobierno->id_vicepresidencia)?'N/A':$solicitanteestructuragobierno->idVicepresidencia->nombre ?></td>
	<td>
		<?= Html::button('Remover',['class'=>'btn btn-xs btn-danger remover-estructura','data-id_estructura_gobierno'=>$solicitanteestructuragobierno->id_estructura_gobierno,'data-id_solicitante'=>$solicitanteestructuragobierno->id_solicitante])?>
	</td>
</tr>

views/smn-solicitantes/_filaContacto.php
<tr>
	<td>
		<?php echo $model->cedula; ?>
		<input type="hidden" name="Contactos[][id_persona]" value="<?php echo $model->id?>">
	</td>
	<td><?php echo $model->nombre." ".$model->apellido ?></td>
	<td><input type="button" value="Remover" class="btn btn-xs btn-danger remover-contacto" data-id="<?php echo $model->id?>" data-cedula="<?php echo $model->cedula?>"></td>
</tr>

views/smn-solicitantes/_formContactos.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\base\Model;
?>

<div class="row">
    <div class="col-md-1" style="padding-top:5px;"> 
    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Cédula</b>
    </div>
    <div class="col-md-2"> 
		<?= Html::textInput('cedula','', [ 'class' => 'form-control solo-numero', 'id' => 'cedula-contacto' ]); ?>
    </div>
    <div class="col-md-4"> 
		<?= Html::button('Buscar', ['class' => 'btn btn-success','id' => 'buscar-persona']) ?>
    </div>   
</div>

<br>

<table id="tabla-contactos" class="table table-bordered">
	<tr class="active">
		<th>Cédula</th>
		<th>Nombre y Apellido</th>
		<th width="10%">Acciones</th>
	</tr>

	<?php if($model->isNewRecord){?>
		<tr id="fila-mensaje">
			<td colspan="3" class="mensaje-tabla">No hay personas registradas</td>
		</tr>
	<?php }?>

	<?php
	if(!$model->isNewRecord){
		$solicitantesContactos=$model->smnSolicitantesContactos;
    	if(count($solicitantesContactos) == 0){
    		?>
    		<tr id="fila-mensaje">
				<td colspan="3" class="mensaje-tabla">No hay personas registradas</td>
			</tr>
    		<?php
    	}else{
            foreach ($solicitantesContactos as $solicitanteContacto){
                $persona=$solicitanteContacto->idPersona;
                ?>
                <tr>
                    <td><?php echo strtoupper($persona->cedula) ?></td>
                    <td><?php echo strtoupper($persona->nombreCompleto) ?></td>
                    <td><input type="button" value="Remover" class="btn btn-xs btn-danger remover-contacto" data-id="<?php echo $persona->id?>" data-cedula="<?php echo $persona->cedula?>"></td>
                </tr>
                <?php
            }
    	}	
	}
	?>
</table>

<?php
/*echo "<pre>";
print_r($model->smnSolicitantesContactos);
echo "</pre>";*/
?>

views/smn-solicitantes/_formRegistro.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\base\Model;
?>

<?= $form->field($model, 'id')->hiddenInput()->label(false); ?>

<div class="row"> 
    <div class="col-md-4"> 
        <?= $form->field($model, 'nombre')->textInput() ?>
    </div>
    <div class="col-md-4">
        <?= $form->field($model, 'nombre_abreviado')->textInput() ?>
    </div>
    <div class="col-md-4">
        <?= $form->field($direccion, 'direccion')->textInput() ?>
    </div> 
</div>
<div class="row">

    <?php if($model->isNewRecord){?>
        <div class="col-md-4">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Correos Electrónicos</legend>
                <div class="listado-items2">
                    <div class="form-group field-correo required">
                        <div class="input-group">
                            <input type="text" id="correo" class="form-control item-validar2" name="SmnCorreos[correo][]" data-accion-validar="/smn-correos/validar-correos">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-success agregar-item2"><i class="glyphicon glyphicon-plus"></i></button>
                            </span>
                        </div>
                        <div class="help-block"></div>
                    </div>
                </div>
            </fieldset>
        </div>

        <div class="col-md-4">
            <fieldset class="scheduler-border">    
                <legend class="scheduler-border">Teléfonos</legend>
                <div class="listado-items2">
                    <div class="form-group field-telefono required">
                        <div class="input-group">
                            <input type="text" id="telefono" class="form-control item-validar2 tlf solo-numero" name="SmnTelefonos[telefono][]" data-accion-validar="/smn-telefonos/validar-telefonos">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-success agregar-item2"><i class="glyphicon glyphicon-plus"></i></button>
                            </span>
                        </div>
                        <div class="help-block"></div>
                    </div> 
                </div>
            </fieldset>
        </div>
    <?php }?>

    <?php if(!$model->isNewRecord){?>
        <div class="col-md-4">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Correos Electrónicos</legend>
                <div id="listado-correos">
                    
                </div>
            </fieldset>
        </div>

        <div class="col-md-4">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Teléfonos</legend>
                <div id="listado-telefonos">
                   
                </div>
            </fieldset>
        </div>
    <?php }?>

</div> 
<div class="row">
    <?php if(!$model->isNewRecord){?>
        <div class="col-md-4">
            <?= $form->field($model, 'activo')->checkbox(); ?>
        </div>
    <?php } ?>
</div>

views/smn-solicitantes/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SmnSolicitantesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="smn-solicitantes-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nombre') ?>

    <?= $form->field($model, 'nombre_abreviado') ?>

    <?= $form->field($model, 'id_direccion') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'tipo')->checkbox() ?>

    <?php // echo $form->field($model, 'activo')->checkbox() ?>

    <?php // echo $form->field($model, 'vicepresidencia')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/smn-solicitantes/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\SmnSolicitantes */

$this->title = 'Registrar Entes Adscritos';
$this->params['breadcrumbs'][] = ['label' => 'Entes Adscritos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="smn-solicitantes-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <!--?= $this->render('_form', [
        'model' => $model,
    ]) ?-->
     <?= $this->render('_form',compact('model','telefonos','correos','direccion','solicitanteestructuragobierno','listestructuragobierno')); ?>


</div>

views/smn-solicitantes/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\SmnSolicitantes */

$this->title = "Consultar Entes Adscritos";
$this->params['breadcrumbs'][] = ['label' => 'Entes Adscritos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="smn-solicitantes-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Modificar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php /*Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ])*/ ?>
    </p>

    <table class="table table-bordered">
        <tr class="active">
            <th width="33%">NOMBRE</th>
            <th width="33%">NOMBRE ABREVIADO</th>
            <th width="34%">DIRECCIÓN</th>
        </tr>

        <tr>
            <td><?php echo strtoupper($model->nombre) ?></td>
            <td><?php echo strtoupper($model->nombre_abreviado) ?></td>
            <td><?php echo $model->idDireccion->direccion ?></td>
        </tr>

        <tr class="active">
            <th>CORREOS ELECTRÓNICOS</th>
            <th>TELÉFONOS</th>
            <th>ESTATUS</th>
        </tr>

        <tr>
            <td>
                <ul>
                    <?php
                    foreach ($model->smnSolicitantesCorreos as $solicitanteCorreo){
                        echo "<li>".$solicitanteCorreo->idCorreo->correo."</li>";
                    }
                    ?>
                </ul>
            </td>
            <td>
                <ul>
                    <?php
                    foreach ($model->smnSolicitantesTelefonos as $solicitanteTelefono){
                        echo "<li>".$solicitanteTelefono->idTelefono->telefono."</li>";
                    }
                    ?>
                </ul>
            </td>
            <td><?php echo $model->activo?"<span class='letra-verde negrita'>ACTIVO</span>":"<span class='letra-roja negrita'>INACTIVO</span>"; ?></td>
        </tr>
    </table>

    <?php
    $estructurasGobiernos=$model->smnSolicitanteEstructuraGobiernos;
    if(count($estructurasGobiernos) > 0){
        ?>
        <br>
        <table class="table table-bordered">
            <tr class="active">
                <th>ESTRUCTURA DE GOBIERNO</th>
                <th>VICEPRESIDENCIA</th>
            </tr>

            <?php
            foreach ($estructurasGobiernos as $estructuraGobierno){
                ?>
                <tr>
                    <td><?php echo $estructuraGobierno->idEstructuraGobierno->nombre ?></td>
                    <td>
                        <?php
                        if(!empty($estructuraGobierno->id_vicepresidencia)){
                            echo $estructuraGobierno->idVicepresidencia->nombre;
                        }else{
                            echo "N/A";
                        }
                        ?>
                    </td>
                </tr>
                <?php
            }
            ?>
        </table>
        <?php
    }
    ?>



    <?php
    $solicitantesContactos=$model->smnSolicitantesContactos;
    if(count($solicitantesContactos) > 0){
        ?>
        <br>
        <table class="table table-bordered">
            <tr class="active">
                <th class="centrar" colspan="3">CONTACTOS</th>
            </tr>

            <tr class="active">
                <th>NOMBRE Y APELLIDO</th>
                <th>TELÉFONOS</th>
                <th>CORREOS ELECTRÓNICOS</th>
            </tr>

            <?php
            foreach ($solicitantesContactos as $solicitanteContacto){
                $persona=$solicitanteContacto->idPersona;
                ?>
                <tr>
                    <td><?php echo strtoupper($persona->nombreCompleto) ?></td>
                    <td>
                        <ul>
                            <?php
                            foreach ($persona->smnPersonasTelefonos as $personaTelefono){
                                echo "<li>".$personaTelefono->telefono->telefono."</li>";
                            }
                            ?>
                        </ul>
                    </td>
                    <td>
                        <ul>
                            <?php
                            foreach ($persona->smnPersonasCorreos as $personaCorreo){
                                echo "<li>".$personaCorreo->correo->correo."</li>";
                            }
                            ?>
                        </ul>
                    </td>
                </tr>
                <?php
            }
            ?>
        </table>
        <?php
    }
    ?>

    <?php
    /*echo "<pre>";
    print_r($model->smnSolicitantesContactos);
    echo "</pre>";*/
    ?>

</div>